-- MySQL Script generated by MySQL Workbench
-- Sat Apr 18 12:39:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`docente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`docente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aula` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aula` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rimborso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rimborso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rimborso` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `euro` INT NOT NULL,
  `docente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rimborso_docente_idx` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `fk_rimborso_docente`
    FOREIGN KEY (`docente_id`)
    REFERENCES `mydb`.`docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`corso_laurea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`corso_laurea` ;

CREATE TABLE IF NOT EXISTS `mydb`.`corso_laurea` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `percorso` VARCHAR(45) NOT NULL,
  `coordinatore` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_corso_laurea_docente1_idx` (`coordinatore` ASC) VISIBLE,
  CONSTRAINT `fk_corso_laurea_docente1`
    FOREIGN KEY (`coordinatore`)
    REFERENCES `mydb`.`docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`studente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`studente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`studente` (
  `matricola` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `corso_laurea_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`matricola`),
  INDEX `fk_studente_corso_laurea1_idx` (`corso_laurea_id` ASC) VISIBLE,
  CONSTRAINT `fk_studente_corso_laurea1`
    FOREIGN KEY (`corso_laurea_id`)
    REFERENCES `mydb`.`corso_laurea` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`corso_materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`corso_materia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`corso_materia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cfu` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `aula_id` INT UNSIGNED NOT NULL,
  `esercitatore` INT UNSIGNED NOT NULL,
  `corso_laurea_id` INT UNSIGNED NOT NULL,
  `docente_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_corso_materia_aula1_idx` (`aula_id` ASC) VISIBLE,
  INDEX `fk_corso_materia_studente1_idx` (`esercitatore` ASC) VISIBLE,
  INDEX `fk_corso_materia_corso_laurea1_idx` (`corso_laurea_id` ASC) VISIBLE,
  INDEX `fk_corso_materia_docente1_idx` (`docente_id` ASC) VISIBLE,
  CONSTRAINT `fk_corso_materia_aula1`
    FOREIGN KEY (`aula_id`)
    REFERENCES `mydb`.`aula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_corso_materia_studente1`
    FOREIGN KEY (`esercitatore`)
    REFERENCES `mydb`.`studente` (`matricola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_corso_materia_corso_laurea1`
    FOREIGN KEY (`corso_laurea_id`)
    REFERENCES `mydb`.`corso_laurea` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_corso_materia_docente1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `mydb`.`docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`esame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`esame` ;

CREATE TABLE IF NOT EXISTS `mydb`.`esame` (
  `studente_matricola` INT UNSIGNED NOT NULL,
  `corso_materia_id` INT UNSIGNED NOT NULL,
  `voto` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`studente_matricola`, `corso_materia_id`),
  INDEX `fk_studente_has_corso_materia_corso_materia1_idx` (`corso_materia_id` ASC) VISIBLE,
  INDEX `fk_studente_has_corso_materia_studente1_idx` (`studente_matricola` ASC) VISIBLE,
  CONSTRAINT `fk_studente_has_corso_materia_studente1`
    FOREIGN KEY (`studente_matricola`)
    REFERENCES `mydb`.`studente` (`matricola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studente_has_corso_materia_corso_materia1`
    FOREIGN KEY (`corso_materia_id`)
    REFERENCES `mydb`.`corso_materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
